<?php

namespace App\Filament\Resources\CardResource\Pages;

use App\Filament\Resources\CardResource;
use App\Filament\Widgets\CardInfoWidget;
use App\Filament\Widgets\TransactionInfoWidget;
use Filament\Actions;
use Filament\Resources\Pages\ContentTabPosition;
use Filament\Resources\Pages\EditRecord;

class EditCard extends EditRecord
{
    protected static string $resource = CardResource::class;

    protected static ?string $breadcrumb = 'Transação';

    protected static ?string $navigationLabel = 'Transações';

    protected static ?string $title = 'Transação';


    protected function getRedirectUrl(): string
    {
        return parent::getResource()::getUrl('index');
    }

    protected function getHeaderActions(): array
    {
        return [
//            Actions\DeleteAction::make(),
        ];
    }

    protected function getFormActions(): array
    {
        return [];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        return $data; // mantém os dados inalterados
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['limit'] = (float) str_replace(',', '.', str_replace('.', '', $data['limit']));

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    public function getTitle(): string
    {
        return $this->record->name ?? parent::getTitle();
    }

    protected function getHeaderWidgets(): array
    {
        return [
            CardInfoWidget::class,
        ];
    }
}
