<?php

namespace App\Filament\Resources\CardResource\Pages;

use App\Filament\Resources\CardResource;
use Filament\Actions;
use Filament\Resources\Pages\ContentTabPosition;
use Filament\Resources\Pages\EditRecord;

class EditCard extends EditRecord
{
    protected static string $resource = CardResource::class;

    protected static ?string $breadcrumb = 'Transação';

    protected static ?string $navigationLabel = 'Transações';

    protected static ?string $title = 'Transação';


    protected function getRedirectUrl(): string
    {
        return parent::getResource()::getUrl('index');
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        return $data; // mantém os dados inalterados
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data['limit'] = (float) str_replace(',', '.', str_replace('.', '', $data['limit']));

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    public function hasCombinedRelationManagerTabsWithContent(): bool
    {
        return true;
    }

    public function getContentTabPosition(): ?ContentTabPosition
    {
        return ContentTabPosition::After;
    }
}
