<?php

namespace App\Filament\Pages;

use App\Filament\Widgets\CountChartWidget;
use App\Filament\Widgets\CountWidget;
use App\Filament\Widgets\PerCardChartWidget;
use App\Filament\Widgets\PerCategoryChartWidget;
use App\Filament\Widgets\UpcomingTransactionsWidget;
use App\Models\Card;
use App\Models\Category;
use App\Models\TransactionItem;
use App\Notifications\UpcomingTransactionItemNotification;
use Carbon\Carbon;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Toggle;
use Filament\Forms\Form;
use Filament\Pages\Dashboard as BaseDashboard;
use Filament\Pages\Dashboard\Concerns\HasFiltersForm;
use Illuminate\Support\Facades\Auth;

class Dashboard extends BaseDashboard
{
    use HasFiltersForm;

    public function mount(): void
    {
        /** @var \App\Models\User $user */
        $user = Auth::user();

        if (!$user) {
            return;
        }

        // Itens com pagamento nos próximos 3 dias
        $items = TransactionItem::query()
            ->whereDate('payment_date', '<=', now()->addDays(3))
            ->whereDate('payment_date', '>=', now())
            ->where('status', '!=', 'PAID')
            ->get();

        if ($items->isNotEmpty() && !$user->unreadNotifications()
                ->where('type', UpcomingTransactionItemNotification::class)
                ->exists()
        ) {
            $user->notify(new UpcomingTransactionItemNotification($items->count()));
        }
    }

    public function getColumns(): int|string|array
    {
        return [
            'sm' => 12,
            'md' => 12,
            'xl' => 12,
        ]; // TODO: Change the autogenerated stub
    }

    public function filtersForm(Form $form): Form
    {
        return $form
            ->schema([
                Section::make()
                    ->schema([
//                        Select::make('category')
//                        ->label('Categoria')
//                            ->options(function () {
//                                return Category::all()->pluck('name', 'id');
//                            }),
                        DatePicker::make('startDate')
                            ->label('Data início')
                            ->default(Carbon::now()->startOfMonth()),
                        DatePicker::make('endDate')
                            ->label('Data fim')
                            ->default(Carbon::now()->endOfMonth()),
//                        Select::make('status')
//                            ->label('Status')
//                            ->searchable()
//                            ->options([
//                                '' => 'Todos',
//                                'PENDING' => 'Pendente',
//                                'PAID' => 'Pago',
//                                'SCHEDULED' => 'Agendado/Débito automático',
//                                'DEBIT' => 'Débito automático',
//                            ])
//                            ->default('')
                    ])
                    ->columns(4),
            ]);
    }

    protected function getFilterFormDefaults(): array
    {
        return [
            'startDate' => Carbon::now()->startOfMonth()->toDateString(),
            'endDate' => Carbon::now()->endOfMonth()->toDateString(),
            'status' => '',
            'category' => null, // ou um ID padrão, se quiser
        ];
    }

    public function getFilters(): array
    {
        return [
            'startDate' => Carbon::now()->startOfMonth()->toDateString(),
            'endDate' => Carbon::now()->endOfMonth()->toDateString(),
            'status' => '',
            'category' => null,
        ];
    }

    public function persistsFiltersInSession(): bool
    {
        return false;
    }

    public function getWidgets(): array
    {
        return [
            CountWidget::class,
            UpcomingTransactionsWidget::class,
            PerCardChartWidget::class,
            CountChartWidget::class,
            PerCategoryChartWidget::class,
        ];
    }
}
