name: Deploy para HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy no servidor
        run: |
          curl -X POST "https://brunotrinchao.com.br/deploy.php?token=kWcqJEoujc79QLBsrgb6AcRO8c"
