name: Run PHPUnit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: |
          cp .env.example .env
          composer install --prefer-dist --no-interaction
          php artisan key:generate

      - name: Prepare database
        run: |
          php artisan migrate --force

      - name: Run tests
        run: |
          php artisan test --parallel
