name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, sqlite, dom
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create SQLite DB
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Copy .env
        run: cp .env.example .env

      - name: Set SQLite config
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=database\/database.sqlite/' .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: ./vendor/bin/phpunit
