name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, sqlite
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copiar .env.example para .env
        run: cp .env.example .env

      - name: Gerar chave de app
        run: php artisan key:generate

      - name: Rodar as migrations
        run: php artisan migrate --env=testing --force

      - name: Rodar testes
        run: php artisan test --env=testing
